guestfs: remove watchdog device from XML file
On f38 KVM host, I get this:

    error: unsupported configuration: unknown watchdog model 'itco'

This is automatically added if QEMU supports it, so remove it from the
XML file and just let QEMU add it.

Signed-off-by: Jeff Layton <jlayton@kernel.org>